export const COMPONENT_IDS = {
  LIST_STUFF_EDIT: 'list-stuff-edit',
  NAVBAR_ADD_HOURS: 'navbar-add-hours',
  NAVBAR_LIST_HOURS: 'navbar-list-hours',
  NAVBAR_ADD_STUFF: 'navbar-add-stuff',
  NAVBAR_LIST_STUFF: 'navbar-list-stuff',
  NAVBAR_LIST_STUFF_ADMIN: 'navbar-list-stuff-admin',
  NAVBAR_CURRENT_USER: 'navbar-current-user',
  NAVBAR_LANDING_PAGE: 'navbar-landing-page',
  NAVBAR_SEARCH: 'navbar-search',
  NAVBAR_HOME: 'navbar-home',
  NAVBAR_BROWSE_OPPORTUNITIES: 'navbar-browse-opportunities',
  NAVBAR_ORGANIZATION_LIBRARY: 'navbar-organization-library',
  NAVBAR_ABOUT_US: 'navbar-about-us',
  NAVBAR_DROPDOWN_ADD_OPPORTUNITY: 'navbar-dropdown-add-opportunity',
  NAVBAR_DROPDOWN_MY_OPPORTUNITY: 'navbar-dropdown-my-opportunity',
  NAVBAR_DROPDOWN_MY_PROFILE: 'navbar-dropdown-my-profile',
  NAVBAR_DROPDOWN_MY_ORGANIZATION_PROFILE: 'navbar-dropdown-my-organization-profile',
  NAVBAR_DROPDOWN_ACCOUNT_SETTINGS: 'navbar-dropdown-account-settings',
  NAVBAR_MESSAGES: 'navbar-messages',
  NAVBAR_MESSAGES_COMPOSE: 'navbar-messages-compose',
  NAVBAR_LOGIN_SIGN_IN: 'navbar-login-sign-in',
  NAVBAR_LOGIN_SIGN_UP: 'navbar-login-sign-up',
  NAVBAR_LOGIN_DROPDOWN: 'navbar-login-dropdown',
  NAVBAR_LOGIN_DROPDOWN_SIGN_IN: 'navbar-login-dropdown-sign-in',
  NAVBAR_LOGIN_DROPDOWN_SIGN_UP: 'navbar-login-dropdown-sign-up',
  NAVBAR_MANAGE_DROPDOWN: 'navbar-manage-dropdown',
  NAVBAR_MANAGE_DROPDOWN_DATABASE: 'navbar-manage-dropdown-database',
  NAVBAR_SIGN_OUT: 'navbar-sign-out',
  SIGN_IN_FORM_EMAIL: 'sign-in-form-email',
  SIGN_IN_FORM_PASSWORD: 'sign-in-form-password',
  SIGN_IN_FORM_SUBMIT: 'sign-in-form-submit',
  SIGN_UP_FORM_EMAIL: 'sign-up-form-email',
  SIGN_UP_FORM_PASSWORD: 'sign-up-form-password',
  SIGN_UP_FORM_FIRST_NAME: 'sign-up-form-first-name',
  SIGN_UP_FORM_LAST_NAME: 'sign-up-form-last-name',
  SIGN_UP_FORM_GENDER: 'sign-up-form-gender',
  SIGN_UP_FORM_ADDRESS: 'sign-up-form-address',
  SIGN_UP_FORM_CITY: 'sign-up-form-city',
  SIGN_UP_FORM_STATE: 'sign-up-form-state',
  SIGN_UP_FORM_ZIP: 'sign-up-form-zip',
  SIGN_UP_FORM_PHONE: 'sign-up-form-phone',
  SIGN_UP_FORM_INTERESTS: 'sign-up-form-interests',
  SIGN_UP_FORM_SKILLS: 'sign-up-form-skills',
  SIGN_UP_FORM_ENVIRONMENT: 'sign-up-form-environmental-preference',
  SIGN_UP_FORM_AVAILABILITY: 'sign-up-form-availability',
  SIGN_UP_FORM_TERM: 'sign-up-form-term',
  SIGN_UP_FORM_SUBMIT: 'sign-up-form-submit',
  // ORG_SIGN_UP_FORM_EMAIL: 'org-sign-up-form-email',
  // ORG_SIGN_UP_FORM_PASSWORD: 'org-sign-up-form-password',
  // ORG_SIGN_UP_FORM_NAME: 'org-sign-up-form-name',
  // ORG_SIGN_UP_FORM_LOCATION: 'org-sign-up-form-location',
  // ORG_SIGN_UP_FORM_WEBSITE: 'org-sign-up-form-website',
  // ORG_SIGN_UP_FORM_AVATAR: 'org-sign-up-form-avatar',
  // ORG_SIGN_UP_FORM_CONTACT_EMAIL: 'org-sign-up-form-contact-email',
  // ORG_SIGN_UP_FORM_CONTACT_NAME: 'org-sign-up-form-contact-name',
  // ORG_SIGN_UP_FORM_CONTACT_ADDRESS: 'org-sign-up-form-contact-address',
  // ORG_SIGN_UP_FORM_CONTACT_PHONE: 'org-sign-up-form-contact-phone',
  // ORG_SIGN_UP_FORM_CATEGORIES: 'org-sign-up-form-categories',
  // ORG_SIGN_UP_FORM_OWNER: 'org-sign-up-form-owner',
  // ORG_SIGN_UP_FORM_STATUS: 'org-sign-up-form-status',
  // ORG_SIGN_UP_FORM_TERM: 'org-sign-up-form-term',
  // ORG_SIGN_UP_FORM_SUBMIT: 'org-sign-up-form-submit',
};
